name: build

on:
  workflow_dispatch:

jobs:
  build:
    uses: murali198/common-workflow/.github/workflows/build-demo.yml@main
    with:
      java_version: "11"
      registry_name: "123"
      image_name: "actions-sample"
    secrets:
      registry_username: "123"
      registry_password: "123"
