name: build

on:
  workflow_dispatch:

jobs:
  build:
    uses: murali198/common-workflow/.github/workflows/java-maven-azure-build.yml@main
    with:
      java_version: "11"
      registry_name: "ofscontainerregistrydev"
      image_name: "actions-sample"
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
