name: deploy

on:
  issue_comment:
    types: [created]

jobs:
  build:
    uses: murali198/common-workflow/.github/workflows/deploy-demo.yml@main
    with:
      cluster_name: "ofsakscluster-dev"
      cluster_resource_group: "ofsmz-aks-rg-dev"
      namespace: "action-test"
      image_name: "actions-sample"
      registry_name: "ofscontainerregistrydev"
      release_name: "actions-test"
      chart_path: "./config/helm/"
      helm_file: "./config/helm/values-dev.yaml"
    secrets:
      azure_cred: "123"
      registry_username: "123"
      registry_password: "123"
